In [1]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
!pip install --upgrade --quiet pip

In [3]:
!pip install --upgrade --quiet datasets[audio] transformers accelerate evaluate jiwer tensorboard gradio

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\Admin\\Desktop\\test\\.venv\\Lib\\site-packages\\transformers\\models\\maskformer\\convert_maskformer_original_pytorch_checkpoint_to_pytorch.py'
Check the permissions.



In [5]:
!pip uninstall numpy

^C


In [21]:
from huggingface_hub import notebook_login

notebook_login()

In [1]:
from datasets import load_dataset, DatasetDict, Dataset

In [2]:
x = []
y = []
with open('train/transcription.txt', 'r', encoding='utf-8') as f:
    temp = f.read()
    lines = temp.split('\n')
    for i in lines:
        sent = i.split(' ')
        x.append(sent[0])
        y.append(' '.join(sent[1:-1]))
    
print(x)
print(y)

['6043_026', '6043_034', '6043_037', '6043_047', '6043_080', '6043_097', '6044_013', '6044_019', '6044_026', '6044_073', '6044_080', '6045_002', '6045_005', '6045_009', '6045_013', '6045_015', '6045_019', '6045_024', '6045_026', '6045_027', '6045_034', '6045_037', '6045_046', '6045_047', '6045_050', '6045_064', '6045_068', '6045_073', '6045_080', '6046_002', '6046_005', '6046_009', '6046_013', '6046_015', '6046_019', '6046_024', '6046_026', '6046_027', '6046_034', '6046_037', '6046_039', '6046_046', '6046_047', '6046_050', '6046_072', '6046_073', '6046_079', '6046_080', '6046_097', '6048_002', '6048_005', '6048_013', '6048_015', '6048_024', '6048_034', '6048_037', '6048_046', '6048_047', '6048_068', '6048_078', '6048_097', '6049_002', '6049_005', '6049_009', '6049_018', '6049_024', '6049_027', '6049_034', '6049_037', '6049_039', '6049_046', '6049_047', '6049_050', '6049_078', '6049_080', '6049_097']
['गुल्शन है जिनके दम से रश्कएजनाँ', 'गुल्शन है जिनके दम से रश्कएजनाँ', 'गुल्शन है जिनके

In [3]:
import wave
from scipy.io import wavfile

In [18]:
tum = (1,2,3)
tum

(1, 2, 3)

In [23]:

import numpy as np
import wave
y_audio = []
for i in x:
    (samplerate, data) = wavfile.read(f'train/audio/{i}.wav')
    data = data.astype(np.float32) / np.iinfo(data.dtype).max
    print(data)
    y_audio.append({
        'path' : f'train/audio/{i}.wav',
        'array' : np.array(data),
        'sampling_rate' : samplerate
    })
    # print(np.array(data).shape())

from datasets import Dataset

train = Dataset.from_dict({
    'audio':y_audio,
    'sentence':y
})
test = Dataset.from_dict({
    'audio':y_audio,
    'sentence':y
})

own_dataset = DatasetDict()
own_dataset['train'] = train
own_dataset['test'] = test

own_dataset

[0.         0.         0.         ... 0.00027467 0.0011597  0.00088504]
[0.         0.         0.         ... 0.00317392 0.00238044 0.00256355]
[ 0.0000000e+00  0.0000000e+00  0.0000000e+00 ... -3.0518509e-05
 -1.2207404e-04 -9.1555528e-05]
[ 0.0000000e+00  0.0000000e+00  3.0518509e-05 ...  4.5777764e-04
 -2.7466659e-04  6.1037019e-05]
[ 0.0000000e+00  0.0000000e+00  3.0518509e-05 ... -1.5259255e-04
  0.0000000e+00  1.8311106e-04]
[0.         0.         0.         ... 0.00595111 0.00985748 0.00613422]
[ 0.0000000e+00  0.0000000e+00  3.0518509e-05 ... -2.1362957e-04
 -1.5259255e-04 -3.0518509e-04]
[ 0.          0.          0.         ...  0.00042726 -0.00097659
 -0.0019837 ]
[ 0.          0.          0.         ... -0.00546281 -0.00537126
 -0.003296  ]
[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 2.4414808e-04 9.1555528e-05
 1.5259255e-04]
[0.         0.         0.         ... 0.00051881 0.00088504 0.00061037]
[ 0.          0.          0.         ...  0.00103763  0.00094607
 -0.002777

DatasetDict({
    train: Dataset({
        features: ['audio', 'sentence'],
        num_rows: 76
    })
    test: Dataset({
        features: ['audio', 'sentence'],
        num_rows: 76
    })
})

In [9]:
# data = DatasetDict()


In [17]:
# train = []
# for i in range(len(x)):
    # features = DatasetDict()
    # features['audio'] = y_audio[i]
    # features['sentence'] = y[i]
#     train.append({
#         'audio':y_audio[i],
#         'sentence':y[i]
#     })

# test = []
# for i in range(len(x)):
    # features = DatasetDict()
    # features['audio'] = y_audio[i]
    # features['sentence'] = y[i]
    # test.append({
    #     'audio':y_audio[i],
    #     'sentence':y[i]
    # })

In [18]:
# dataset = DatasetDict()
# dataset['train'] = train
# dataset['test'] = test


In [24]:
own_dataset

DatasetDict({
    train: Dataset({
        features: ['audio', 'sentence'],
        num_rows: 76
    })
    test: Dataset({
        features: ['audio', 'sentence'],
        num_rows: 76
    })
})

In [ ]:
from datasets import load_dataset, DatasetDict

common_voice = DatasetDict()

common_voice["train"] = load_dataset("mozilla-foundation/common_voice_11_0", "hi", split="train+validation", use_auth_token=True)
common_voice["test"] = load_dataset("mozilla-foundation/common_voice_11_0", "hi", split="test", use_auth_token=True)

print(common_voice)

In [5]:
common_voice = common_voice.remove_columns(["accent", "age", "client_id", "down_votes", "gender", "locale", "path", "segment", "up_votes"])

print(common_voice)

DatasetDict({
    train: Dataset({
        features: ['audio', 'sentence'],
        num_rows: 6540
    })
    test: Dataset({
        features: ['audio', 'sentence'],
        num_rows: 2894
    })
})


In [25]:
own_dataset['train'][0]

{'audio': {'array': [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   -3.0518509447574615e-05,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   3.0518509447574615e-05,
   3.0518509447574615e-05,
   3.0518509447574615e-05,
   3.0518509447574615e-05,
   3.0518509447574615e-05,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   

In [6]:
# dictt = {
#     'train': [
#         'features':{
#             'audio':[1,2,3],
#             'sent':'234234'
#         },
#         'num_rows':12
#     ],
#     'test':[
#         'features':{
#             'audio':[1,2,3],
#             'sent':'234234'
#         },
#         'num_rows':12
#     ]
# }

In [35]:
from transformers import WhisperFeatureExtractor

feature_extractor = WhisperFeatureExtractor.from_pretrained("openai/whisper-tiny")

In [27]:
from transformers import WhisperTokenizer

tokenizer = WhisperTokenizer.from_pretrained("openai/whisper-tiny", language="Hindi", task="transcribe")

tokenizer_config.json:   0%|          | 0.00/283k [00:00<?, ?B/s]

c:\Users\Admin\Desktop\test\.venv\lib\site-packages\huggingface_hub\file_download.py:148: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Admin\.cache\huggingface\hub\models--openai--whisper-tiny. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


vocab.json:   0%|          | 0.00/836k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.48M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/494k [00:00<?, ?B/s]

normalizer.json:   0%|          | 0.00/52.7k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.19k [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [28]:
from transformers import WhisperProcessor

processor = WhisperProcessor.from_pretrained("openai/whisper-tiny", language="Hindi", task="transcribe")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [29]:
own_dataset

DatasetDict({
    train: Dataset({
        features: ['audio', 'sentence'],
        num_rows: 76
    })
    test: Dataset({
        features: ['audio', 'sentence'],
        num_rows: 76
    })
})

In [33]:
print(common_voice["train"][0])

{'audio': {'path': 'C:\\Users\\Admin\\.cache\\huggingface\\datasets\\downloads\\extracted\\135eaa4f2263da7a294667a823874dc1fa8ab91eea15917132d8af509eafacc5\\hi_train_0/common_voice_hi_26008353.mp3', 'array': array([ 6.46234854e-26, -1.35709319e-25, -8.07793567e-26, ...,
        1.06425944e-07,  4.46417090e-08,  2.61451660e-09]), 'sampling_rate': 48000}, 'sentence': 'हमने उसका जन्मदिन मनाया।'}


In [30]:
print(own_dataset['train'][0])

{'audio': {'array': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -3.0518509447574615e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0518509447574615e-05, 3.0518509447574615e-05, 3.0518509447574615e-05, 3.0518509447574615e-05, 3.0518509447574615e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

In [31]:
from datasets import Audio

own_dataset = own_dataset.cast_column("audio", Audio(sampling_rate=16000))

In [32]:
print(own_dataset['train'][0])

{'audio': {'path': None, 'array': array([ 2.33673200e-06,  2.49370351e-06, -2.44659896e-06, ...,
        1.25281268e-03,  8.87902454e-04,  3.46472574e-04]), 'sampling_rate': 16000}, 'sentence': 'गुल्शन है जिनके दम से रश्कएजनाँ'}


In [36]:
from datasets import Audio

common_voice = common_voice.cast_column("audio", Audio(sampling_rate=16000))

In [36]:
feature_extractor

WhisperFeatureExtractor {
  "chunk_length": 30,
  "feature_extractor_type": "WhisperFeatureExtractor",
  "feature_size": 80,
  "hop_length": 160,
  "n_fft": 400,
  "n_samples": 480000,
  "nb_max_frames": 3000,
  "padding_side": "right",
  "padding_value": 0.0,
  "processor_class": "WhisperProcessor",
  "return_attention_mask": false,
  "sampling_rate": 16000
}

In [37]:
def prepare_dataset(batch):
    # load and resample audio data from 48 to 16kHz
    audio = batch["audio"]

    # compute log-Mel input features from input audio array
    batch["input_features"] = feature_extractor(np.array(audio["array"]), sampling_rate=audio["sampling_rate"]).input_features[0]

    # encode target text to label ids
    batch["labels"] = tokenizer(batch["sentence"]).input_ids
    return batch

In [39]:
own_dataset = own_dataset.map(prepare_dataset, remove_columns=own_dataset.column_names["train"])

Map:   0%|          | 0/76 [00:00<?, ? examples/s]

Map:   0%|          | 0/76 [00:00<?, ? examples/s]

In [40]:
own_dataset

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 76
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 76
    })
})

In [14]:
common_voice = common_voice.map(prepare_dataset, remove_columns=common_voice.column_names["train"], num_proc=2)

/usr/local/lib/python3.10/dist-packages/multiprocess/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()


Map (num_proc=2):   0%|          | 0/6540 [00:00<?, ? examples/s]

Map (num_proc=2):   0%|          | 0/2894 [00:00<?, ? examples/s]

In [41]:
from transformers import WhisperForConditionalGeneration

model = WhisperForConditionalGeneration.from_pretrained("openai/whisper-tiny")

config.json:   0%|          | 0.00/1.98k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/151M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/3.75k [00:00<?, ?B/s]

In [42]:
model.generation_config.language = "hindi"
model.generation_config.task = "transcribe"

model.generation_config.forced_decoder_ids = None

In [114]:
dataset = []
for i in range(len(data['x_train'])):
    dataset.append({
        'input_feature' : list(data['x_train'][i]),
        'label': data['y'][i]
    })

train_data = DatasetDict(dataset)

In [43]:
import torch

from dataclasses import dataclass
from typing import Any, Dict, List, Union

@dataclass
class DataCollatorSpeechSeq2SeqWithPadding:
    processor: Any
    decoder_start_token_id: int

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        # split inputs and labels since they have to be of different lengths and need different padding methods
        # first treat the audio inputs by simply returning torch tensors
        input_features = [{"input_features": feature["input_features"]} for feature in features]
        batch = self.processor.feature_extractor.pad(input_features, return_tensors="pt")

        # get the tokenized label sequences
        label_features = [{"input_ids": feature["labels"]} for feature in features]
        # pad the labels to max length
        labels_batch = self.processor.tokenizer.pad(label_features, return_tensors="pt")

        # replace padding with -100 to ignore loss correctly
        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)

        # if bos token is appended in previous tokenization step,
        # cut bos token here as it's append later anyways
        if (labels[:, 0] == self.decoder_start_token_id).all().cpu().item():
            labels = labels[:, 1:]

        batch["labels"] = labels

        return batch

In [44]:
data_collator = DataCollatorSpeechSeq2SeqWithPadding(
    processor=processor,
    decoder_start_token_id=model.config.decoder_start_token_id,
)

In [45]:
import evaluate

metric = evaluate.load("wer")

In [46]:
def compute_metrics(pred):
    pred_ids = pred.predictions
    label_ids = pred.label_ids

    # replace -100 with the pad_token_id
    label_ids[label_ids == -100] = tokenizer.pad_token_id

    # we do not want to group tokens when computing the metrics
    pred_str = tokenizer.batch_decode(pred_ids, skip_special_tokens=True)
    label_str = tokenizer.batch_decode(label_ids, skip_special_tokens=True)

    wer = 100 * metric.compute(predictions=pred_str, references=label_str)

    return {"wer": wer}

In [68]:
from transformers import Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir= 'train',  # change to a repo name of your choice
    per_device_train_batch_size=16,
    gradient_accumulation_steps=1,  # increase by 2x for every 2x decrease in batch size
    learning_rate=1e-5,
    warmup_steps=500,
    num_train_epochs=10,
    gradient_checkpointing=True,
    fp16=False,
    evaluation_strategy="steps",
    per_device_eval_batch_size=8,
    predict_with_generate=True,
    generation_max_length=225,
    save_steps=1,
    eval_steps=1,
    logging_steps=1,
    report_to=["tensorboard"],
    load_best_model_at_end=True,
    metric_for_best_model="wer",
    greater_is_better=False,
    # push_to_hub=True,
)

**Note**: if one does not want to upload the model checkpoints to the Hub,
set `push_to_hub=False`.

We can forward the training arguments to the 🤗 Trainer along with our model,
dataset, data collator and `compute_metrics` function:

In [69]:
training_args.output_dir

'train'

In [70]:
from transformers import Seq2SeqTrainer

trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=own_dataset['train'],
    eval_dataset=own_dataset["test"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    tokenizer=processor.feature_extractor,
)

In [71]:
processor.save_pretrained(training_args.output_dir)

[]

In [ ]:
trainer.train()

In [ ]:
kwargs = {
    "dataset_tags": "mozilla-foundation/common_voice_11_0",
    "dataset": "Common Voice 11.0",  # a 'pretty' name for the training dataset
    "dataset_args": "config: hi, split: test",
    "language": "hi",
    "model_name": "Whisper Small Hi - Sanchit Gandhi",  # a 'pretty' name for our model
    "finetuned_from": "openai/whisper-small",
    "tasks": "automatic-speech-recognition",
}

The training results can now be uploaded to the Hub. To do so, execute the `push_to_hub` command and save the preprocessor object we created:

In [ ]:
trainer.push_to_hub(**kwargs)

## Building a Demo

Now that we've fine-tuned our model we can build a demo to show
off its ASR capabilities! We'll make use of 🤗 Transformers
`pipeline`, which will take care of the entire ASR pipeline,
right from pre-processing the audio inputs to decoding the
model predictions.

Running the example below will generate a Gradio demo where we
can record speech through the microphone of our computer and input it to
our fine-tuned Whisper model to transcribe the corresponding text:

In [ ]:
from transformers import pipeline
import gradio as gr

pipe = pipeline(model="sanchit-gandhi/whisper-small-hi")  # change to "your-username/the-name-you-picked"

def transcribe(audio):
    text = pipe(audio)["text"]
    return text

iface = gr.Interface(
    fn=transcribe,
    inputs=gr.Audio(source="microphone", type="filepath"),
    outputs="text",
    title="Whisper Small Hindi",
    description="Realtime demo for Hindi speech recognition using a fine-tuned Whisper small model.",
)

iface.launch()

## Closing Remarks

In this blog, we covered a step-by-step guide on fine-tuning Whisper for multilingual ASR
using 🤗 Datasets, Transformers and the Hugging Face Hub. For more details on the Whisper model, the Common Voice dataset and the theory behind fine-tuning, refere to the accompanying [blog post](https://huggingface.co/blog/fine-tune-whisper). If you're interested in fine-tuning other
Transformers models, both for English and multilingual ASR, be sure to check out the
examples scripts at [examples/pytorch/speech-recognition](https://github.com/huggingface/transformers/tree/main/examples/pytorch/speech-recognition).